### PR TITLE
add deprecation note about seasons and periods

### PR DESCRIPTION
**Pull request by Azdaroth**
Looks like that: http://share.bookingsync.com/3z2m3t1c443w

### CODE REVIEW

**Comment by thilonel** [comment]
How about something shorter and less confusing? Along the lines of:
> By August 1, for Rentals with Rates managed by a third party through NightlyRateMap, Seasons and Periods will stop being a reliable source for rates and minimum stays. Please switch to using...

**Comment by Azdaroth** [comment]
@thilonel This is exactly the same thing that was sent to Partners, I think it makes sense to add that extra background.

**Comment by thilonel** [comment]
I think the wording is too complicated. Maybe we can start with something like what I wrote and then go into details like with what you wrote?

**Comment by Azdaroth** [comment]
@thilonel So how would that exactly sound?

**Comment by thilonel** [comment]
On 1 August 2018 Seasons and Periods will no longer be a reliable source for rates and minimum stays for Rentals with rates managed by a third party through Nightly Rate Maps, as we'll stop generating them from the maps.
We advise you to start using the Nightly Rates Maps endpoint instead.
Rates Rules and Rentals Fees will keep using Seasons and Periods.
If you need any further assistance, please reach out to apisupport@bookingsync.com.

**Pull request merged**
