### PR TITLE
CORE-240 remove comment about bookings create validation

### PR DESCRIPTION
**Pull request by thilonel**
I would not advertise this validation feature, and it doesn't work like this anymore.

### CODE REVIEW

**Comment by thilonel** [comment]
It works, but not like the comment says.
If you send final price, we validate it by the content of the request.
if you don't, we calculate it based on the data you're sending.

The final price is not computed in the way the comment says either.

**Comment by Azdaroth** [comment]
So maybe it would be good to mention how it exactly works instead of just removing it?

**Comment by thilonel** [comment]
I don't want to promote this validation to be honest. Final price should be a read only thing, you provide all the data and we return the final price.

**Comment by Azdaroth** [comment]
@thilonel Hmm, ok, actually that's how it works in our UI - you can't set final price, it's read only.

**Pull request merged**
