### PR TITLE
Update Search rentals scope response

### PR DESCRIPTION
**Pull request by hash4di**
Screenshots:
bookingsync api documentation_old
bookingsync api documentation_new

Table of Search rentals response parameters:
screen shot 2015-10-15 at 12 08 23

### CODE REVIEW

**Comment by Azdaroth** [comment]
I think we should add another section with explanation, what actually is being returned here. I mean it's not really obvious what this response actually include, why there are 2 types of taxes etc, basically like `Parameters` section.

price to pay now is price of the booking if it was to be booked now, initial price is price of the rental, final price is rental price + fees + taxes + discounts, rentals fees are the required rentals fees to be booked with the rental, taxes are merged taxes from all taxable types (either Rental or Fee), price details consists of fees details, which are the fees that are required to be booked and taxes, which is the detailed breakdown of taxes and where they come from (the top-level taxes basically group these taxes and sum them).

**Comment by hash4di** [comment]
Added to PR description screenshot of new table with Search Rentals response parameters.

**Comment by Azdaroth** [comment]
:+1:

**Comment by Fredar** [comment]
I am not sure about the table looks.
I need to give this some though.

**Comment by Fredar** [comment]
@hash4di please reuse existing nested styling from here http://developers.bookingsync.com/reference/endpoints/clients/

**Comment by hash4di** [comment]
Preview of updated styling with small reordering for improve readability:

screen shot 2015-10-26 at 15 44 44

**Comment by hash4di** [comment]
@Fredar how about now?

**Comment by hash4di** [comment]
Move wrong pasted attributes:
 
screen shot 2015-10-26 at 16 16 48

**Comment by hash4di** [comment]
Fixed and rebased

screen shot 2015-10-26 at 16 51 42

**Pull request merged**
